#!/usr/bin/env bash
set -euo pipefail

export RUBY_FILES=$(git diff origin/main --cached --name-only --diff-filter MRA *.{rb,rake})
export XPP_FILES=$(git diff origin/main --cached --name-only --diff-filter MRA *.{cpp,hpp})

dx/exec -t bundle exec rake ci:documentation

if [[ -n $RUBY_FILES ]]; then
  dx/exec -t bundle exec rake ci:formatting:jobs:standard
fi

if [[ -n $XPP_FILES ]]; then
  dx/exec -t bundle exec rake ci:formatting:jobs:clang_format
  dx/exec -t bundle exec rake ci:linting
fi
