FROM debian:12 AS asdf_install

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV ASDF_VERSION=v0.14.1
ENV PATH="/home/me/.asdf/shims:/home/me/.asdf/bin:$PATH"

WORKDIR /home/me/app

COPY .tool-versions /home/me/.tool-versions

RUN <<SETUP
apt-get update --quiet --yes

BASE_DEPS="curl git"
RUBY_DEPS="ruby-build libffi-dev libyaml-dev"
LINUX_BUILD_DEPS="build-essential "

apt-get install --quiet --yes \
  ${BASE_DEPS} \
  ${RUBY_DEPS} \
  ${LINUX_BUILD_DEPS}
SETUP

RUN <<LOGIN
groupadd --gid ${GROUP_ID} mygroup
useradd -ms /bin/bash me --uid ${USER_ID} --gid ${GROUP_ID}
chown -R me /home/me
LOGIN

USER me

RUN git clone https://github.com/asdf-vm/asdf.git /home/me/.asdf --branch ${ASDF_VERSION}

RUN asdf plugin-add ruby && asdf install ruby

FROM debian:12

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV PATH="/home/me/.asdf/shims:/home/me/.asdf/bin:$PATH"

RUN <<SETUP
apt-get update --quiet --yes

BASE_DEPS="curl git clang-format clang-tidy"
DEV_TOOLS="sudo valgrind gdb vim"
RUBY_DEPS="ruby-build libffi-dev libyaml-dev"
LINUX_BUILD_DEPS="build-essential "
WINDOWS_BUILD_DEPS="mingw-w64"
TEST_DEPS="alsa-utils openbox unzip wget xdotool xvfb"
WINDOWS_TEST_DEPS="wine"
WEB_TEST_DEPS="firefox-esr"

apt-get install --quiet --yes \
  ${BASE_DEPS} \
  ${DEV_TOOLS} \
  ${RUBY_DEPS} \
  ${LINUX_BUILD_DEPS} \
  ${WINDOWS_BUILD_DEPS} \
  ${TEST_DEPS} \
  ${WINDOWS_TEST_DEPS} \
  ${WEB_TEST_DEPS}
SETUP

ARG PCM_DEVICE="hw:0,3"
ARG PCM_CARD="0"

RUN <<AUDIO
cat << EOF > /etc/asound.conf
pcm.!default {
        type plug
        slave {
                pcm "${PCM_DEVICE}"
        }
}

ctl.!default {
        type hw
        card ${PCM_CARD}
}
AUDIO

WORKDIR /home/me/app

# Setup the group and user to match your local system
RUN <<LOGIN
groupadd --gid ${GROUP_ID} mygroup
useradd -ms /bin/bash me --uid ${USER_ID} --gid ${GROUP_ID} --password $(perl -e 'print crypt($ARGV[0], "password")' 'password') 
adduser me audio
adduser me sudo
chown -R me /home/me
LOGIN

USER me

RUN echo "source /home/me/.asdf/asdf.sh" >> /home/me/.bashrc && \
  echo "source /home/me/.asdf/completions/asdf.bash" >> /home/me/.bashrc

COPY --from=asdf_install /home/me/.asdf /home/me/.asdf
COPY .tool-versions /home/me/.tool-versions

RUN gem install bundler && \
  bundle config set path vendor/bundle

CMD ["sleep", "infinity"]
