FROM debian:13 AS asdf_install

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV ASDF_VERSION=v0.18.0
ENV ASDF_PLATFORM=amd64
ENV ASDF_URL=https://github.com/asdf-vm/asdf/releases/download/$ASDF_VERSION/asdf-$ASDF_VERSION-linux-$ASDF_PLATFORM.tar.gz
ENV PATH="/home/me/.asdf/shims:/home/me/.asdf/bin:$PATH"

WORKDIR /home/me/app

COPY .tool-versions /home/me/.tool-versions

RUN <<SETUP
apt-get update --quiet --yes

BASE_DEPS="wget curl git"
RUBY_DEPS="ruby-build libffi-dev libyaml-dev"
LINUX_BUILD_DEPS="build-essential "

apt-get install --quiet --yes \
  ${BASE_DEPS} \
  ${RUBY_DEPS} \
  ${LINUX_BUILD_DEPS}
SETUP

RUN <<LOGIN
groupadd --gid ${GROUP_ID} mygroup
useradd -ms /bin/bash me --uid ${USER_ID} --gid ${GROUP_ID}
chown -R me /home/me
LOGIN

USER me

RUN <<ASDF
wget -O /home/me/asdf.tar.gz "${ASDF_URL}"
tar xfv /home/me/asdf.tar.gz
mkdir -p /home/me/.asdf/bin/
mv asdf /home/me/.asdf/bin/asdf
ASDF

RUN asdf plugin add ruby && asdf install ruby

FROM debian:13

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV PATH="/home/me/.asdf/shims:/home/me/.asdf/bin:$PATH"

RUN <<SETUP
apt-get update --quiet --yes

BASE_DEPS="curl git bear"
LLVM_DEPS="lsb-release gnupg"
RUBY_DEPS="ruby-build libffi-dev libyaml-dev"
LINUX_BUILD_DEPS="build-essential "
WINDOWS_BUILD_DEPS="mingw-w64"
TEST_DEPS="unzip wget"
WINDOWS_TEST_DEPS="wine"
WEB_TEST_DEPS="firefox-esr"

apt-get install --quiet --yes \
  ${BASE_DEPS} \
  ${LLVM_DEPS} \
  ${RUBY_DEPS} \
  ${LINUX_BUILD_DEPS} \
  ${WINDOWS_BUILD_DEPS} \
  ${TEST_DEPS} \
  ${WINDOWS_TEST_DEPS} \
  ${WEB_TEST_DEPS}
SETUP

RUN <<LLVM
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
./llvm.sh 21

apt-get install --quiet --yes \
  clang-format-21 \
  clang-tidy-21

ln -s $(which clang-format-21) /usr/local/bin/clang-format
ln -s $(which clang-tidy-21) /usr/local/bin/clang-tidy
LLVM

WORKDIR /home/me/app

# Setup the group and user to match your local system
RUN <<LOGIN
groupadd --gid ${GROUP_ID} mygroup
useradd -ms /bin/bash me --uid ${USER_ID} --gid ${GROUP_ID} --password $(perl -e 'print crypt($ARGV[0], "password")' 'password') 
adduser me sudo
chown -R me /home/me
LOGIN

USER me

COPY --from=asdf_install /home/me/.asdf /home/me/.asdf
COPY .tool-versions /home/me/.tool-versions

RUN <<SETUP
echo "export PATH=\"${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH\"" >> /home/me/.bashrc
echo ". <(asdf completion bash)" >> /home/me/.bashrc

gem install bundler
bundle config set path vendor/bundle
SETUP

CMD ["sleep", "infinity"]
