FROM debian:12

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV ASDF_VERSION=v0.14.1
ENV RUBY_VERSION=latest
ENV PATH="/home/me/.asdf/shims:/home/me/.asdf/bin:$PATH"

RUN apt-get update --quiet --yes

RUN apt-get install --quiet --yes curl git

# Install linux build dependencies
RUN apt-get install --quiet --yes \
      build-essential \
      clang-format \
      clang-tidy

# Install dependencies for ruby compilation
RUN apt-get install --quiet --yes ruby-build libffi-dev libyaml-dev

# Setup audio test
RUN <<SHELL
  cat << EOF > /etc/asound.conf
pcm.!default {
        type plug
        slave {
                pcm "hw:0,3"
        }
}

ctl.!default {
        type hw
        card 0
}
EOF
SHELL

# Install base test dependencies
RUN \
  apt-get install -y --no-install-recommends \
    openbox \
    unzip \
    wget \
    xdotool \
    xvfb

# Install windows test dependencies
RUN \
  apt-get install -y --no-install-recommends \
    mingw-w64 \
    wine

# Install web test dependencies
RUN \
  apt-get install -y --no-install-recommends \
    firefox-esr

WORKDIR /home/me/app

# Setup the group and user to match your local system
RUN groupadd --gid ${GROUP_ID} mygroup && \
  useradd -ms /bin/bash me --uid ${USER_ID} --gid ${GROUP_ID} && \
  chown -R me /home/me

USER me

RUN echo "source /home/me/.asdf/asdf.sh" >> /home/me/.bashrc && \
  echo "source /home/me/.asdf/completions/asdf.bash" >> /home/me/.bashrc

RUN git clone https://github.com/asdf-vm/asdf.git /home/me/.asdf --branch ${ASDF_VERSION}

RUN asdf plugin-add ruby && asdf install ruby ${RUBY_VERSION} && asdf global ruby ${RUBY_VERSION}

RUN gem install bundler && \
  bundle config set path /home/me/gems

CMD ["sleep", "infinity"]
