FROM debian:stable-slim

WORKDIR /app

ENV PATH="/app/emsdk:/app/emsdk/node/14.15.5_64bit/bin:/app/emsdk/upstream/emscripten:${PATH}"

# Libraries are in order
# 1. Core
# 2. Exporting

RUN \
  apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    git \
    libatomic1 \
    ruby \
    python3 \
    xz-utils \
    \
    zip && \
  apt-get clean && apt-get autoremove -y

RUN  git clone https://github.com/juj/emsdk.git /app/emsdk &&\
  cd /app/emsdk &&\
  ./emsdk install 2.0.33 &&\
  ./emsdk activate 2.0.33
