FROM debian:stable-slim

WORKDIR /app

ENV PATH="/app/emsdk:/app/emsdk/node/14.15.5_64bit/bin:/app/emsdk/upstream/emscripten:${PATH}"

# Libraries are in order
# 1. Core
# 2. Exporting

RUN \
  apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    git \
    libatomic1 \
    ruby \
    python3 \
    xz-utils \
    \
    locales \
    zip && \
  apt-get clean -y && apt-get autoremove -y && \
  \
  sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8

RUN  git clone https://github.com/juj/emsdk.git /app/emsdk &&\
  cd /app/emsdk &&\
  ./emsdk install 3.1.8 &&\
  ./emsdk activate 3.1.8
