steps:
  - label: 'Taylor Build'
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake linux:release:build
      - cd dist/linux/release
      - buildkite-agent artifact upload taylor

  - wait

  - label: 'CLI Tool Tests'
    artifact_paths:
      - ./cli-tool/test-analytics.json
    commands:
      - buildkite-agent artifact download taylor /usr/bin/
      - chmod +x /usr/bin/taylor
      - cd ./cli-tool/
      - taylor ./cli.rb test/test.rb
      - ../.buildkite/scripts/tests/upload_test_analytics.sh ./test-analytics.json

  - label: 'Taylor Tests - Export'
    commands:
      - buildkite-agent artifact download taylor /usr/bin/
      - chmod +x /usr/bin/taylor
      - .buildkite/scripts/tests/export.sh

  - wait

  - label: 'Taylor Tests - Linux'
    artifact_paths:
      - tmp/test-analytics.json
    commands:
      - .buildkite/scripts/tests/test_suite_linux.sh
      - .buildkite/scripts/tests/upload_test_analytics.sh ./tmp/test-analytics.json

  - label: 'Taylor Tests - Windows'
    artifact_paths:
      - tmp/test-analytics.json
    commands:
      - .buildkite/scripts/tests/test_suite_windows.sh
      - .buildkite/scripts/tests/upload_test_analytics.sh ./tmp/test-analytics.json

  - label: 'Taylor Tests - Web'
    artifact_paths:
      - tmp/test-analytics.json
    commands:
      - .buildkite/scripts/tests/test_suite_web.sh
      - .buildkite/scripts/tests/upload_test_analytics.sh ./tmp/test-analytics.json
