FROM taylor/build-web AS build_base
WORKDIR /app/export
# I'm not really sure why but EM_CACHE is required for the docker export to work on OSX.
ENV \
  PATH="/app/emsdk:/app/emsdk/node/14.15.5_64bit/bin:/app/emsdk/upstream/emscripten:${PATH}" \
  EM_CACHE="/app/emsdk/upstream/emscripten/cache"

COPY --from=taylor/export /usr/bin/taylor /app/mruby/bin/mrbc /usr/bin/
COPY --from=taylor/export /app/taylor /app/taylor
COPY . /app/export

ENV \
  USER_ID=1000 \
  GROUP_ID=1000 \
  EXPORT=web \
  LANG=en_US.UTF-8 \
  LANGUAGE=en_US.UTF-8 \
  LC_ALL=en_US.UTF-8

CMD ["./entrypoint.sh"]
