FROM taylor/build-web as build_base
WORKDIR /app/export
ENV PATH="/app/emsdk:/app/emsdk/node/14.15.5_64bit/bin:/app/emsdk/upstream/emscripten:${PATH}"
# I'm not really sure why but this is required for the docker export to work on OSX.
ENV EM_CACHE="/app/emsdk/upstream/emscripten/cache"

# This seems to take a really long time on some machines, so let's leave it as
# a separate step to keep rebuild times low.
RUN chmod -R o+w \
    /app/emsdk

COPY --from=taylor/export /app/taylor /app/taylor
COPY --from=taylor/export /app/mruby/bin/mrbc /bin/
COPY . /app/export

RUN chmod -R o+w \
    /app/export \
    /app/taylor \
    /app/taylor/include

ENV EXPORT=web
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

CMD ["./entrypoint.sh"]
