FROM taylor/build-android AS build_base
WORKDIR /app/export

COPY --from=taylor/export /usr/bin/taylor /app/mruby/bin/mrbc /usr/bin/
COPY --from=taylor/export /app/taylor /app/taylor
COPY . /app/export

ENV \
  USER_ID=1000 \
  GROUP_ID=1000 \
  EXPORT=android \
  LANG=en_US.UTF-8 \
  LANGUAGE=en_US.UTF-8 \
  LC_ALL=en_US.UTF-8

RUN dpkg-reconfigure locales

CMD ["./entrypoint.sh"]
