FROM taylor/build-windows as build_base
WORKDIR /app/export

COPY --from=taylor/export /app/taylor /app/taylor
COPY --from=taylor/export /app/mruby/bin/mrbc /bin/

COPY . /app/export

RUN chmod -R o+w \
    /app/export \
    /app/taylor \
    /app/taylor/include

ENV EXPORT=windows

CMD ["./entrypoint.sh"]
