FROM taylor/build-osx AS build_base
WORKDIR /app/export

COPY --from=taylor/export /usr/bin/taylor /usr/bin/taylor
COPY --from=taylor/export /app/taylor /app/taylor
COPY --from=taylor/export /app/mruby/bin/mrbc /bin/

COPY . /app/export

RUN chmod -R o+w \
    /app/export \
    /app/taylor \
    /app/taylor/include

ENV \
  EXPORT=osx \
  LANG=en_US.UTF-8 \
  LANGUAGE=en_US.UTF-8 \
  LC_ALL=en_US.UTF-8

CMD ["./entrypoint.sh"]
