require 'json'
require 'fileutils'

require './lib/squasher'

options = {
  'name' => 'taylor_game',
  'version' => 'v0.0.1',
  'input' => 'game.rb',
  'export_directory' => './exports',
  'load_paths' => [
    './',
    './vendor',
  ],
  'copy_paths' => [
    './assets',
  ],
}

if File.exists?('../game/taylor-config.json')
  options.merge!(
    JSON.parse(File.read('../game/taylor-config.json'))
  )
end

task :build do
  sh "docker build . --pull --tag hellrok/taylor"
end

task :squash do
  Dir.chdir('../game')
  puts `ls -l`
  Squasher.call(options)
  Dir.chdir('../export')
end

task :transpile => :squash
task :transpile do
  sh "/app/mruby/bin/mrbc -Bgame -o game.h ./output.rb"
end

task :rename do
  Dir.chdir('../game')
  FileUtils.mkdir_p options['export_directory']

  puts "Copying linux build"

  FileUtils.mkdir_p File.join(options['export_directory'], 'linux')
  FileUtils.cp '../taylor/dist/linux/release/taylor',
    File.join('./', options['export_directory'], 'linux', options['name'])

  puts "Copying windows build"

  FileUtils.mkdir_p File.join(options['export_directory'], 'windows')
  FileUtils.cp '../taylor/dist/windows/release/taylor.exe',
    File.join('./', options['export_directory'], 'windows', "#{options['name']}.exe")
  FileUtils.cp Dir.glob('../taylor/dist/windows/release/*.dll'),
    File.join('./', options['export_directory'], 'windows')

  puts "Copying osx build"

  app_path = File.join(
    options['export_directory'],
    'osx',
    "#{options['name']}.app",
    'Contents',
    'MacOS'
  )
  FileUtils.mkdir_p(app_path)
  FileUtils.cp '../taylor/dist/osx/release/taylor',
    File.join(app_path, options['name'])
end

task :compress do
  Dir.chdir(options['export_directory'])

  Dir.chdir('./linux')
  options['copy_paths'].each { |asset_path| FileUtils.cp_r(File.join('/app/game/', asset_path), '.') }
  sh "zip -r #{options['name']}-linux-#{options['version']}.zip *"

  Dir.chdir('../windows')
  options['copy_paths'].each { |asset_path| FileUtils.cp_r(File.join('/app/game/', asset_path), '.') }
  sh "zip -r #{options['name']}-windows-#{options['version']}.zip *"

  Dir.chdir('../osx')
  app_path = File.join('.', "#{options['name']}.app", 'Contents', 'MacOS')
  FileUtils.mkdir_p(app_path)
  File.write(File.join(app_path, '..', 'PkgInfo'), 'APPL????APPL????')
  options['copy_paths'].each { |asset_path| FileUtils.cp_r(File.join('/app/game/', asset_path), app_path) }
  sh "zip -r #{options['name']}-osx-#{options['version']}.zip *"

  Dir.chdir('..')
  sh "mv **/*.zip ./"
  sh "rm -rf linux windows osx"
end
