services:
  app:
    image: ${IMAGE}
    init: true
    user: "me"
    volumes:
      - type: "bind"
        source: "../../"
        target: "/home/me/app"
    devices:
      - /dev/snd:/dev/snd
    ports:
      - "3001:3000"
