services:
  app:
    image: ${IMAGE}
    init: true
    user: "me"
    volumes:
      - type: "bind"
        source: "../../"
        target: "/home/me/app"
      - type: "bind"
        source: "//var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: "bind"
        source: "/tmp/taylor-builds"
        target: "/tmp/taylor-builds"
    devices:
      - /dev:/dev
    privileged: true
